package com.yjb.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yjb.dao.table.GroupMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUP_MESSAGE".
*/
public class GroupMessageDao extends AbstractDao<GroupMessage, String> {

    public static final String TABLENAME = "GROUP_MESSAGE";

    /**
     * Properties of entity GroupMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property FirstMessageId = new Property(1, String.class, "firstMessageId", false, "FIRST_MESSAGE_ID");
        public final static Property LastMessageId = new Property(2, String.class, "lastMessageId", false, "LAST_MESSAGE_ID");
        public final static Property FromUserId = new Property(3, Integer.class, "fromUserId", false, "FROM_USER_ID");
        public final static Property FromUserName = new Property(4, String.class, "fromUserName", false, "FROM_USER_NAME");
        public final static Property FromUserNickName = new Property(5, String.class, "fromUserNickName", false, "FROM_USER_NICK_NAME");
        public final static Property FromUserHeadImage = new Property(6, String.class, "fromUserHeadImage", false, "FROM_USER_HEAD_IMAGE");
        public final static Property GroupId = new Property(7, Long.class, "groupId", false, "GROUP_ID");
        public final static Property GroupName = new Property(8, String.class, "groupName", false, "GROUP_NAME");
        public final static Property GroupHeadImage = new Property(9, String.class, "groupHeadImage", false, "GROUP_HEAD_IMAGE");
        public final static Property ChatMessage = new Property(10, String.class, "chatMessage", false, "CHAT_MESSAGE");
        public final static Property MessageType = new Property(11, Integer.class, "messageType", false, "MESSAGE_TYPE");
        public final static Property ViewMessageType = new Property(12, Integer.class, "viewMessageType", false, "VIEW_MESSAGE_TYPE");
        public final static Property SendTime = new Property(13, Long.class, "sendTime", false, "SEND_TIME");
        public final static Property UnreadCount = new Property(14, Long.class, "unreadCount", false, "UNREAD_COUNT");
        public final static Property Readed = new Property(15, Boolean.class, "readed", false, "READED");
        public final static Property UseNoDisturb = new Property(16, Boolean.class, "useNoDisturb", false, "USE_NO_DISTURB");
        public final static Property HandType = new Property(17, int.class, "handType", false, "HAND_TYPE");
        public final static Property Receiverd = new Property(18, boolean.class, "receiverd", false, "RECEIVERD");
        public final static Property QiangDao = new Property(19, boolean.class, "qiangDao", false, "QIANG_DAO");
        public final static Property ShowTime = new Property(20, boolean.class, "showTime", false, "SHOW_TIME");
        public final static Property MsgState = new Property(21, int.class, "msgState", false, "MSG_STATE");
        public final static Property NotifyUser = new Property(22, String.class, "notifyUser", false, "NOTIFY_USER");
    }


    public GroupMessageDao(DaoConfig config) {
        super(config);
    }
    
    public GroupMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUP_MESSAGE\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"FIRST_MESSAGE_ID\" TEXT," + // 1: firstMessageId
                "\"LAST_MESSAGE_ID\" TEXT," + // 2: lastMessageId
                "\"FROM_USER_ID\" INTEGER NOT NULL ," + // 3: fromUserId
                "\"FROM_USER_NAME\" TEXT," + // 4: fromUserName
                "\"FROM_USER_NICK_NAME\" TEXT," + // 5: fromUserNickName
                "\"FROM_USER_HEAD_IMAGE\" TEXT," + // 6: fromUserHeadImage
                "\"GROUP_ID\" INTEGER NOT NULL ," + // 7: groupId
                "\"GROUP_NAME\" TEXT," + // 8: groupName
                "\"GROUP_HEAD_IMAGE\" TEXT," + // 9: groupHeadImage
                "\"CHAT_MESSAGE\" TEXT," + // 10: chatMessage
                "\"MESSAGE_TYPE\" INTEGER NOT NULL ," + // 11: messageType
                "\"VIEW_MESSAGE_TYPE\" INTEGER," + // 12: viewMessageType
                "\"SEND_TIME\" INTEGER NOT NULL ," + // 13: sendTime
                "\"UNREAD_COUNT\" INTEGER," + // 14: unreadCount
                "\"READED\" INTEGER," + // 15: readed
                "\"USE_NO_DISTURB\" INTEGER," + // 16: useNoDisturb
                "\"HAND_TYPE\" INTEGER NOT NULL ," + // 17: handType
                "\"RECEIVERD\" INTEGER NOT NULL ," + // 18: receiverd
                "\"QIANG_DAO\" INTEGER NOT NULL ," + // 19: qiangDao
                "\"SHOW_TIME\" INTEGER NOT NULL ," + // 20: showTime
                "\"MSG_STATE\" INTEGER NOT NULL ," + // 21: msgState
                "\"NOTIFY_USER\" TEXT);"); // 22: notifyUser
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUP_MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GroupMessage entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String firstMessageId = entity.getFirstMessageId();
        if (firstMessageId != null) {
            stmt.bindString(2, firstMessageId);
        }
 
        String lastMessageId = entity.getLastMessageId();
        if (lastMessageId != null) {
            stmt.bindString(3, lastMessageId);
        }
        stmt.bindLong(4, entity.getFromUserId());
 
        String fromUserName = entity.getFromUserName();
        if (fromUserName != null) {
            stmt.bindString(5, fromUserName);
        }
 
        String fromUserNickName = entity.getFromUserNickName();
        if (fromUserNickName != null) {
            stmt.bindString(6, fromUserNickName);
        }
 
        String fromUserHeadImage = entity.getFromUserHeadImage();
        if (fromUserHeadImage != null) {
            stmt.bindString(7, fromUserHeadImage);
        }
        stmt.bindLong(8, entity.getGroupId());
 
        String groupName = entity.getGroupName();
        if (groupName != null) {
            stmt.bindString(9, groupName);
        }
 
        String groupHeadImage = entity.getGroupHeadImage();
        if (groupHeadImage != null) {
            stmt.bindString(10, groupHeadImage);
        }
 
        String chatMessage = entity.getChatMessage();
        if (chatMessage != null) {
            stmt.bindString(11, chatMessage);
        }
        stmt.bindLong(12, entity.getMessageType());
 
        Integer viewMessageType = entity.getViewMessageType();
        if (viewMessageType != null) {
            stmt.bindLong(13, viewMessageType);
        }
        stmt.bindLong(14, entity.getSendTime());
 
        Long unreadCount = entity.getUnreadCount();
        if (unreadCount != null) {
            stmt.bindLong(15, unreadCount);
        }
 
        Boolean readed = entity.getReaded();
        if (readed != null) {
            stmt.bindLong(16, readed ? 1L: 0L);
        }
 
        Boolean useNoDisturb = entity.getUseNoDisturb();
        if (useNoDisturb != null) {
            stmt.bindLong(17, useNoDisturb ? 1L: 0L);
        }
        stmt.bindLong(18, entity.getHandType());
        stmt.bindLong(19, entity.getReceiverd() ? 1L: 0L);
        stmt.bindLong(20, entity.getQiangDao() ? 1L: 0L);
        stmt.bindLong(21, entity.getShowTime() ? 1L: 0L);
        stmt.bindLong(22, entity.getMsgState());
 
        String notifyUser = entity.getNotifyUser();
        if (notifyUser != null) {
            stmt.bindString(23, notifyUser);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GroupMessage entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String firstMessageId = entity.getFirstMessageId();
        if (firstMessageId != null) {
            stmt.bindString(2, firstMessageId);
        }
 
        String lastMessageId = entity.getLastMessageId();
        if (lastMessageId != null) {
            stmt.bindString(3, lastMessageId);
        }
        stmt.bindLong(4, entity.getFromUserId());
 
        String fromUserName = entity.getFromUserName();
        if (fromUserName != null) {
            stmt.bindString(5, fromUserName);
        }
 
        String fromUserNickName = entity.getFromUserNickName();
        if (fromUserNickName != null) {
            stmt.bindString(6, fromUserNickName);
        }
 
        String fromUserHeadImage = entity.getFromUserHeadImage();
        if (fromUserHeadImage != null) {
            stmt.bindString(7, fromUserHeadImage);
        }
        stmt.bindLong(8, entity.getGroupId());
 
        String groupName = entity.getGroupName();
        if (groupName != null) {
            stmt.bindString(9, groupName);
        }
 
        String groupHeadImage = entity.getGroupHeadImage();
        if (groupHeadImage != null) {
            stmt.bindString(10, groupHeadImage);
        }
 
        String chatMessage = entity.getChatMessage();
        if (chatMessage != null) {
            stmt.bindString(11, chatMessage);
        }
        stmt.bindLong(12, entity.getMessageType());
 
        Integer viewMessageType = entity.getViewMessageType();
        if (viewMessageType != null) {
            stmt.bindLong(13, viewMessageType);
        }
        stmt.bindLong(14, entity.getSendTime());
 
        Long unreadCount = entity.getUnreadCount();
        if (unreadCount != null) {
            stmt.bindLong(15, unreadCount);
        }
 
        Boolean readed = entity.getReaded();
        if (readed != null) {
            stmt.bindLong(16, readed ? 1L: 0L);
        }
 
        Boolean useNoDisturb = entity.getUseNoDisturb();
        if (useNoDisturb != null) {
            stmt.bindLong(17, useNoDisturb ? 1L: 0L);
        }
        stmt.bindLong(18, entity.getHandType());
        stmt.bindLong(19, entity.getReceiverd() ? 1L: 0L);
        stmt.bindLong(20, entity.getQiangDao() ? 1L: 0L);
        stmt.bindLong(21, entity.getShowTime() ? 1L: 0L);
        stmt.bindLong(22, entity.getMsgState());
 
        String notifyUser = entity.getNotifyUser();
        if (notifyUser != null) {
            stmt.bindString(23, notifyUser);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public GroupMessage readEntity(Cursor cursor, int offset) {
        GroupMessage entity = new GroupMessage( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // firstMessageId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lastMessageId
            cursor.getInt(offset + 3), // fromUserId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // fromUserName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // fromUserNickName
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // fromUserHeadImage
            cursor.getLong(offset + 7), // groupId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // groupName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // groupHeadImage
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // chatMessage
            cursor.getInt(offset + 11), // messageType
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // viewMessageType
            cursor.getLong(offset + 13), // sendTime
            cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14), // unreadCount
            cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0, // readed
            cursor.isNull(offset + 16) ? null : cursor.getShort(offset + 16) != 0, // useNoDisturb
            cursor.getInt(offset + 17), // handType
            cursor.getShort(offset + 18) != 0, // receiverd
            cursor.getShort(offset + 19) != 0, // qiangDao
            cursor.getShort(offset + 20) != 0, // showTime
            cursor.getInt(offset + 21), // msgState
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22) // notifyUser
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GroupMessage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setFirstMessageId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLastMessageId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFromUserId(cursor.getInt(offset + 3));
        entity.setFromUserName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFromUserNickName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFromUserHeadImage(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setGroupId(cursor.getLong(offset + 7));
        entity.setGroupName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setGroupHeadImage(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setChatMessage(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setMessageType(cursor.getInt(offset + 11));
        entity.setViewMessageType(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setSendTime(cursor.getLong(offset + 13));
        entity.setUnreadCount(cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14));
        entity.setReaded(cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0);
        entity.setUseNoDisturb(cursor.isNull(offset + 16) ? null : cursor.getShort(offset + 16) != 0);
        entity.setHandType(cursor.getInt(offset + 17));
        entity.setReceiverd(cursor.getShort(offset + 18) != 0);
        entity.setQiangDao(cursor.getShort(offset + 19) != 0);
        entity.setShowTime(cursor.getShort(offset + 20) != 0);
        entity.setMsgState(cursor.getInt(offset + 21));
        entity.setNotifyUser(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
     }
    
    @Override
    protected final String updateKeyAfterInsert(GroupMessage entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(GroupMessage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GroupMessage entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
